spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lynn?serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


###########################mybatis配置###############################
#全局映射器启用缓存
# mybatis.configuration.cache-enabled=true
#查询时,关闭关联对象及时加载以提高性能
#mybatis.configuration.lazy-loading-enabled=false
#按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
#mybatis.configuration.aggressive-lazy-loading=false
#允许返回不同的结果集以达到通用的效果
#mybatis.configuration.multiple-result-sets-enabled=true
#对于批量更新操作缓存SQL以提高性能
#mybatis.configuration.default-executor-type=REUSE
#数据库执行超时时间
#mybatis.configuration.default-statement-timeout=25000
#mybatis.mapper-locations=classpath:mapping/*.xml
#mybatis.type-aliases-package=com.etc.po
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true